---
title: "Lab 05 - Wrangling spatial data"
author: "Anaelle Gackiere"
date: "02-13-2026"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox) 
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
```

### Exercise 1

```{r filter-alaska}

# Filter the Denny’s df for Alaska
dn_ak <- dennys %>%
  filter(state == "AK")
nrow(dn_ak)

# Filter the La Quinta df for Alaska
lq_ak <- laquinta %>%
  filter(state == "AK")
nrow(lq_ak)


```

There are `r nrow(dn_ak)` Denny's locations in Alaska and `r nrow(lq_ak)`La Quinta locations in Alaska. 

### Exercise 2

```{r AK-DNandLQ-pairings}
# Calculate the number of pairings using the data frames you have already made

n_pairings <- nrow(dn_ak) * nrow(lq_ak)
n_pairings

```

There are `r nrow(dn_ak) * nrow(lq_ak)` pairings to be made.

### Exercise 3

```{r}





```




...

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...

Add exercise headings as needed.
